{
 "title": "Chia Server",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "xch_eur",
    "label": "XCH-EUR",
    "query": "SELECT last(\"EUR\") FROM \"sensor.xch\" WHERE (\"entity_id\" = 'xch')"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Farmed",
     "measurement": "chia",
     "select": [
      [
       { "params": [ "Totalchiafarmed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Pool Payout",
     "measurement": "http",
     "select": [
      [
       { "params": [ "totalPaidInXCH" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Pending Balance",
     "measurement": "http",
     "select": [
      [
       { "params": [ "unpaidBalanceInXCH" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Payout (€)",
     "measurement": "http",
     "select": [
      [
       { "params": [ "totalPaidInXCH" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* $xch_eur" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Plots",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total #",
     "measurement": "chia",
     "select": [
      [
       { "params": [ "Plotcountforallharvesters" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total TiB",
     "measurement": "chia",
     "select": [
      [
       { "params": [ "Totalsizeofplots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Pool plots",
     "measurement": "filecount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Farm",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Exp. Time to Win",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chia",
     "select": [
      [
       { "params": [ "Expectedtimetowin" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*30" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Eligable p/min.",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "farm_logs",
     "select": [
      [
       { "params": [ "eligible_plots" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "30" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "Partials p/hour",
     "measurement": "farm_logs",
     "select": [
      [
       { "params": [ "proofs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 3" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pool",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Rank",
     "measurement": "http",
     "select": [
      [
       { "params": [ "rank" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Points",
     "measurement": "http",
     "select": [
      [
       { "params": [ "pendingPoints" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Difficulty",
     "measurement": "http",
     "select": [
      [
       { "params": [ "lastDifficulty" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Estimated Plots",
     "measurement": "http",
     "select": [
      [
       { "params": [ "estimatedPlots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU",
     "measurement": "cpu",
     "query": "SELECT last(\"usage_idle\") * -1 + 100 - last(\"usage_iowait\") FROM \"cpu\" WHERE (\"cpu\" = 'cpu-total') AND $timeFilter",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "IO-Wait",
     "measurement": "cpu",
     "query": "SELECT last(\"usage_iowait\") FROM \"cpu\" WHERE (\"cpu\" = 'cpu-total') AND $timeFilter",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "CPU Temp",
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "nct6798_peciagent0calibration_input"
      }
     ]
    },
    {
     "alias": "RAM",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NVME Temp.",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "nvme0-s1",
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "nvme0n1" }
     ]
    },
    {
     "alias": "nvme0-s2",
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "nvme0n1" }
     ]
    },
    {
     "alias": "nvme1-s1",
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "nvme1n1" }
     ]
    },
    {
     "alias": "nvme1-s2",
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "nvme1n1" }
     ]
    }
   ]
  },
  {
   "title": "Net space (1 week)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "chia",
     "select": [
      [
       { "params": [ "Estimatednetworkspace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1024" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tmp Drives - IO %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "980pro-IO%",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "io %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ID_MODEL", "operator": "=", "value": "Samsung SSD 980 PRO 1TB" }
     ]
    },
    {
     "alias": "Intel-SSD-IO%",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "io %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ID_MODEL", "operator": "=", "value": "INTEL_SSDSC2BX80" }
     ]
    }
   ]
  },
  {
   "title": "Tmp Drives - disk usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used_percent\")  / 100 FROM \"disk\" WHERE (\"path\" =~ /md[3-9]/) AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/md[1-9]/" }
     ]
    }
   ]
  },
  {
   "title": "Eligable plots",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Elg. plots",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "farm_logs",
     "query": "SELECT \"plot_phase_time\" FROM \"plot_logs\" WHERE (\"plot_phase\" = '1' AND \"path\" =~  /.*980pro.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "eligible_plots" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "Proof time",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "farm_logs",
     "query": "SELECT \"plot_phase_time\" FROM \"plot_logs\" WHERE (\"plot_phase\" = '1' AND \"path\" =~  /.*980pro.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "proof_time" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Proofs",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "farm_logs",
     "query": "SELECT \"plot_phase_time\" FROM \"plot_logs\" WHERE (\"plot_phase\" = '1' AND \"path\" =~  /.*980pro.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "proofs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Plots per day",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Daily plots",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "plot_logs",
     "query": "SELECT \"plot_phase_time\" FROM \"plot_logs\" WHERE (\"plot_phase\" = '1' AND \"path\" =~  /.*980pro.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "plot_total_time" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Plot total time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_job",
     "groupBy": [
      { "params": [ "job" ], "type": "tag" }
     ],
     "measurement": "plot_logs",
     "query": "SELECT \"plot_phase_time\" FROM \"plot_logs\" WHERE (\"plot_phase\" = '1' AND \"path\" =~  /.*980pro.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "plot_total_time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU & RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"usage_active\") - last(\"usage_iowait\") FROM \"cpu\" WHERE (\"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "usage_active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "alias": "RAM",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "io-wait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"usage_active\") - last(\"usage_iowait\") FROM \"cpu\" WHERE (\"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "[[tag_ID_FS_LABEL]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ID_FS_LABEL" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "io %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ID_FS_LABEL", "operator": "=~", "value": "/hdd[0-9]/" }
     ]
    },
    {
     "alias": "md3",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "io %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "nvme0n1p1" }
     ]
    },
    {
     "alias": "md1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "io %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/sd[h|i|j|k]1/" }
     ]
    },
    {
     "alias": "md2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "io %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ID_MODEL", "operator": "=", "value": "INTEL_SSDSC2BX80" }
     ]
    },
    {
     "alias": "md4",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "io %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "nvme1n1p1" }
     ]
    }
   ]
  },
  {
   "title": "Plot phase time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "1-[[tag_job]]",
     "groupBy": [
      { "params": [ "job" ], "type": "tag" }
     ],
     "measurement": "plot_logs",
     "query": "SELECT \"plot_phase_time\" FROM \"plot_logs\" WHERE (\"plot_phase\" = '1' AND \"path\" =~  /.*980pro.*/) AND $timeFilter",
     "select": [
      [
       { "params": [ "plot_phase_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "plot_phase", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "2-[[tag_job]]",
     "groupBy": [
      { "params": [ "job" ], "type": "tag" }
     ],
     "measurement": "plot_logs",
     "query": "SELECT \"plot_phase_time\" FROM \"plot_logs\" WHERE (\"plot_phase\" = '2' AND \"path\" = '/home/rom/Swar-Chia-Plot-Manager/logs/980pro_2021-05-24_22_30_56_094393.log') AND $timeFilter",
     "select": [
      [
       { "params": [ "plot_phase_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "plot_phase", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "3-[[tag_job]]",
     "groupBy": [
      { "params": [ "job" ], "type": "tag" }
     ],
     "measurement": "plot_logs",
     "select": [
      [
       { "params": [ "plot_phase_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "plot_phase", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "4-[[tag_job]]",
     "groupBy": [
      { "params": [ "job" ], "type": "tag" }
     ],
     "measurement": "plot_logs",
     "select": [
      [
       { "params": [ "plot_phase_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "plot_phase", "operator": "=", "value": "4" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ],
      [
       { "params": [ "used" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/hdd[0-9]/" }
     ]
    }
   ]
  },
  {
   "title": "IO MB/sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Wrt-[[tag_ID_FS_LABEL]]",
     "groupBy": [
      { "params": [ "ID_FS_LABEL" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "ID_FS_LABEL", "operator": "=~", "value": "/(hdd|md|sas)[0-9]/" }
     ]
    },
    {
     "alias": "Read-[[tag_ID_FS_LABEL]]",
     "groupBy": [
      { "params": [ "ID_FS_LABEL" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "ID_FS_LABEL", "operator": "=~", "value": "/(hdd|md|sas)[0-9]/" }
     ]
    }
   ]
  },
  {
   "title": "HDD Temp.",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "hddtemp",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/sd[a-i]/" }
     ]
    }
   ]
  },
  {
   "title": "HDD Temp.",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "hddtemp",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/sd[j-z]/" }
     ]
    }
   ]
  }
 ]
}